//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientLourd.ItineraryServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ItineraryServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRoute", ReplyAction="http://tempuri.org/IService1/GetRouteResponse")]
        string GetRoute(string start, string dest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRoute", ReplyAction="http://tempuri.org/IService1/GetRouteResponse")]
        System.Threading.Tasks.Task<string> GetRouteAsync(string start, string dest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAdresse", ReplyAction="http://tempuri.org/IService1/GetAdresseResponse")]
        string GetAdresse(string adresse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAdresse", ReplyAction="http://tempuri.org/IService1/GetAdresseResponse")]
        System.Threading.Tasks.Task<string> GetAdresseAsync(string adresse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCoordonnees", ReplyAction="http://tempuri.org/IService1/GetCoordonneesResponse")]
        string GetCoordonnees(string adresse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCoordonnees", ReplyAction="http://tempuri.org/IService1/GetCoordonneesResponse")]
        System.Threading.Tasks.Task<string> GetCoordonneesAsync(string adresse);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ClientLourd.ItineraryServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ClientLourd.ItineraryServiceReference.IService1>, ClientLourd.ItineraryServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string GetRoute(string start, string dest) {
            return base.Channel.GetRoute(start, dest);
        }
        
        public System.Threading.Tasks.Task<string> GetRouteAsync(string start, string dest) {
            return base.Channel.GetRouteAsync(start, dest);
        }
        
        public string GetAdresse(string adresse) {
            return base.Channel.GetAdresse(adresse);
        }
        
        public System.Threading.Tasks.Task<string> GetAdresseAsync(string adresse) {
            return base.Channel.GetAdresseAsync(adresse);
        }
        
        public string GetCoordonnees(string adresse) {
            return base.Channel.GetCoordonnees(adresse);
        }
        
        public System.Threading.Tasks.Task<string> GetCoordonneesAsync(string adresse) {
            return base.Channel.GetCoordonneesAsync(adresse);
        }
    }
}
