//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TdRest.ProxyBikeSOAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyBikeSOAP.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetContract", ReplyAction="http://tempuri.org/IService1/GetContractResponse")]
        string GetContract(string adresse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetContract", ReplyAction="http://tempuri.org/IService1/GetContractResponse")]
        System.Threading.Tasks.Task<string> GetContractAsync(string adresse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCoordonees", ReplyAction="http://tempuri.org/IService1/GetCoordoneesResponse")]
        string GetCoordonees(string adresse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCoordonees", ReplyAction="http://tempuri.org/IService1/GetCoordoneesResponse")]
        System.Threading.Tasks.Task<string> GetCoordoneesAsync(string adresse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getParcours", ReplyAction="http://tempuri.org/IService1/getParcoursResponse")]
        string getParcours(double lat1, double lng1, double lat2, double lng2, bool isCycling);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getParcours", ReplyAction="http://tempuri.org/IService1/getParcoursResponse")]
        System.Threading.Tasks.Task<string> getParcoursAsync(double lat1, double lng1, double lat2, double lng2, bool isCycling);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TdRest.ProxyBikeSOAP.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TdRest.ProxyBikeSOAP.IService1>, TdRest.ProxyBikeSOAP.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetContract(string adresse) {
            return base.Channel.GetContract(adresse);
        }
        
        public System.Threading.Tasks.Task<string> GetContractAsync(string adresse) {
            return base.Channel.GetContractAsync(adresse);
        }
        
        public string GetCoordonees(string adresse) {
            return base.Channel.GetCoordonees(adresse);
        }
        
        public System.Threading.Tasks.Task<string> GetCoordoneesAsync(string adresse) {
            return base.Channel.GetCoordoneesAsync(adresse);
        }
        
        public string getParcours(double lat1, double lng1, double lat2, double lng2, bool isCycling) {
            return base.Channel.getParcours(lat1, lng1, lat2, lng2, isCycling);
        }
        
        public System.Threading.Tasks.Task<string> getParcoursAsync(double lat1, double lng1, double lat2, double lng2, bool isCycling) {
            return base.Channel.getParcoursAsync(lat1, lng1, lat2, lng2, isCycling);
        }
    }
}
